export const DESTINATIONS = [
  {
    id: "kosi",
    no: "01",
    name: "Kosi Fan",
    place: "Bihar",
    kind: "Disaster",
    line: "Cloud-affected optical plus SAR. The query a district officer actually asks.",
    flight: "Optical × SAR",
    image: "/missions/kosi-optical.jpg",
    card: "/space/journey-kosi.png",
    site: "S2 + S1",
    coords: "25.87°N · 86.60°E",
    sensor: "Sentinel-2 · Sentinel-1",
    date: "18 Jul 2020",
    task: "Flood VQA",
    label: "Kosi / Optical–SAR fusion",
    proves: "Cross-modal flood · settlement grounding",
  },
  {
    id: "mundra",
    no: "02",
    name: "Mundra",
    place: "Gujarat",
    kind: "Infrastructure",
    line: "A working harbour. Ground the ships and tanks the sentence named.",
    flight: "Single optical",
    image: "/missions/mundra-port.jpg",
    card: "/space/journey-mundra.png",
    site: "VHR",
    coords: "22.74°N · 69.71°E",
    sensor: "Cartosat class",
    date: "12 Nov 2023",
    task: "Grounding",
    label: "Mundra / Text-guided grounding",
    proves: "VQA · captioning · object boxes",
  },
  {
    id: "gurgaon",
    no: "03",
    name: "Gurugram",
    place: "Haryana",
    kind: "Change",
    line: "Thirty-three years apart. Increase, decrease, or unchanged — with a map.",
    flight: "Two dates",
    image: "/missions/gurgaon-now.jpg",
    card: "/space/journey-gurgaon.png",
    site: "L5 + VHR",
    coords: "28.46°N · 77.03°E",
    sensor: "Landsat · VHR",
    date: "1991 → 2024",
    task: "Change VQA",
    label: "Gurugram / Bi-temporal change",
    proves: "Change mask · description · VQA",
  },
  {
    id: "doaba",
    no: "04",
    name: "Doaba",
    place: "Punjab",
    kind: "Agriculture",
    line: "The mandatory baseline: land-cover caption and VQA on one MSI chip.",
    flight: "Single optical",
    image: "/missions/punjab-fields.jpg",
    card: "/missions/punjab-fields.jpg",
    site: "S2-MSI",
    coords: "30.84°N · 75.88°E",
    sensor: "Sentinel-2 MSI",
    date: "10 Feb 2024",
    task: "Caption",
    label: "Doaba / Scene captioning",
    proves: "Captioning · land-cover VQA",
  },
] as const;

export type Destination = (typeof DESTINATIONS)[number];

export const LABS = [
  {
    no: "01",
    title: "Multi-Sensor Data Ingestion",
    body: "It seamlessly processes both synthetic aperture radar (SAR) and multispectral optical imagery to analyze complex Earth Observation data.",
  },
  {
    no: "02",
    title: "Geographically Anchored Captioning",
    body: "It automatically generates highly accurate text descriptions detailing specific land-use and land-cover classes present in satellite patches.",
  },
  {
    no: "03",
    title: "Visual Question Answering (VQA)",
    body: "It answers direct user queries about uploaded satellite images through both binary and multiple-choice conversational formats.",
  },
  {
    no: "04",
    title: "Spatial Grounding and Detection",
    body: "It visually pinpoints user-requested geographical features directly on the image using precise bounding box predictions.",
  },
  {
    no: "05",
    title: "Factual Knowledge Retrieval (RAG)",
    body: "It dynamically pulls external scientific metadata and geographical records to ensure all image analysis is grounded in real-world facts.",
  },
] as const;

export const PS_COVER = [
  { k: "Vision-Language Model", v: "Handles complex VQA, reasoning, and captioning across multiple modalities." },
  { k: "Earth Foundation Model", v: "Specialized encoder for satellite imagery and multi-temporal features." },
  { k: "Spatial Detection Model", v: "Pinpoints features with precise bounding boxes and segmentation masks." },
  { k: "RAG Engine", v: "Retrieves external geographical and scientific context to ground answers." },
] as const;
