export const DESTINATIONS = [
  {
    id: "kosi",
    no: "01",
    name: "Kosi Fan",
    place: "Bihar",
    kind: "Disaster",
    line: "Cloud-affected optical plus SAR. The query a district officer actually asks.",
    flight: "Optical × SAR",
    image: "/missions/kosi-optical.jpg",
    card: "/space/journey-kosi.png",
    site: "S2 + S1",
    coords: "25.87°N · 86.60°E",
    sensor: "Sentinel-2 · Sentinel-1",
    date: "18 Jul 2020",
    task: "Flood VQA",
    label: "Kosi / Optical–SAR fusion",
    proves: "Cross-modal flood · settlement grounding",
  },
  {
    id: "mundra",
    no: "02",
    name: "Mundra",
    place: "Gujarat",
    kind: "Infrastructure",
    line: "A working harbour. Ground the ships and tanks the sentence named.",
    flight: "Single optical",
    image: "/missions/mundra-port.jpg",
    card: "/space/journey-mundra.png",
    site: "VHR",
    coords: "22.74°N · 69.71°E",
    sensor: "Cartosat class",
    date: "12 Nov 2023",
    task: "Grounding",
    label: "Mundra / Text-guided grounding",
    proves: "VQA · captioning · object boxes",
  },
  {
    id: "gurgaon",
    no: "03",
    name: "Gurugram",
    place: "Haryana",
    kind: "Change",
    line: "Thirty-three years apart. Increase, decrease, or unchanged — with a map.",
    flight: "Two dates",
    image: "/missions/gurgaon-now.jpg",
    card: "/space/journey-gurgaon.png",
    site: "L5 + VHR",
    coords: "28.46°N · 77.03°E",
    sensor: "Landsat · VHR",
    date: "1991 → 2024",
    task: "Change VQA",
    label: "Gurugram / Bi-temporal change",
    proves: "Change mask · description · VQA",
  },
  {
    id: "doaba",
    no: "04",
    name: "Doaba",
    place: "Punjab",
    kind: "Agriculture",
    line: "The mandatory baseline: land-cover caption and VQA on one MSI chip.",
    flight: "Single optical",
    image: "/missions/punjab-fields.jpg",
    card: "/missions/punjab-fields.jpg",
    site: "S2-MSI",
    coords: "30.84°N · 75.88°E",
    sensor: "Sentinel-2 MSI",
    date: "10 Feb 2024",
    task: "Caption",
    label: "Doaba / Scene captioning",
    proves: "Captioning · land-cover VQA",
  },
] as const;

export type Destination = (typeof DESTINATIONS)[number];

export const LABS = [
  {
    no: "01",
    title: "Multi-Sensor Data Ingestion",
    body: "It seamlessly processes both synthetic aperture radar (SAR) and multispectral optical imagery to analyze complex Earth Observation data.",
  },
  {
    no: "02",
    title: "Visual Question Answering (VQA)",
    body: "It automatically generates highly accurate text descriptions detailing specific land-use and land-cover classes present in satellite patches.",
  },
  {
    no: "03",
    title: "Intelligent Model Routing",
    body: "Automatically selects the appropriate specialized model for each query, enabling more accurate multimodal analysis",
  },
  {
    no: "04",
    title: "Spatial Grounding and Detection",
    body: "It visually pinpoints user-requested geographical features directly on the image using precise bounding box predictions.",
  },
] as const;

export const PS_COVER = [
  { k: "VQA", model: "Qwen2.5-VL", v: "Satellite image question answering and scene description using optical or SAR imagery." },
  { k: "Grounding", model: "Grounding DINO + SAM 2", v: "Text-guided object localization and pixel-level segmentation for identifying requested regions." },
  { k: "Bi-Temporal Analysis", model: "ChangeFormer + Qwen2.5-VL", v: "Detects changes between images captured at different times and generates natural-language change descriptions." },
  { k: "SAR + Optical Analysis", model: "CROMA + Qwen2.5-VL", v: "Fuses SAR and optical imagery to extract complementary information and provide context-aware analysis." },
] as const;
